import type { Metadata } from "next";
import "./globals.css";
import { Left } from "./components/left/Left";
import { Right } from "./components/right/right";
import { Bottom } from "./components/bottom/Bottom";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/LoGo.png"></link>
      </head>
      <body>
        <div className="relative">
          <div className="sm:container sm:mx-auto w-auto mx-[15px]">
            <div className="flex gap-[20px]">
              <Left />
              <div className="flex-1 py-[20px] mb-[100px]">
                <Right />
                <main>
                  {children}
                </main>
              </div>
            </div>
          </div>
          <Bottom />
        </div>
      </body>
    </html>
  );
}
